In [1]:
import numpy as np
import math
from scipy.stats import multivariate_normal
from sklearn.neighbors import NearestNeighbors
import random 

In [2]:
a = np.array([i for i in range(100)])
b = np.array([(i*2 +5)*3 for i in range(100)])

In [3]:
def cos_sim(A, B):
    denominator = np.dot(A,B)
    nummeraotor = math.sqrt((A.T@A * B.T@B))    
    return denominator/nummeraotor

In [4]:
cos_sim(b, a)

0.9997757815947825

## Top n approach

In [5]:
def knn_euclidean(train_matrix, test_matrix, k):
    neightbor = {}
    for i in range(len(test_matrix)):
        dist = np.linalg.norm((train_matrix - test_matrix[i].T), axis= 1)
        topk = np.argsort(dist)[:k]
        neightbor[i] = topk
    return neightbor

In [6]:
def knn_cosine(train_matrix, test_matrix, k):
    neightbor = {}
    norm_train = np.linalg.norm(train_matrix, axis = 1)
    norm_test = np.linalg.norm(test_matrix, axis = 1)
    for i in range(len(test_matrix)):
        cos = (train_matrix @ test_matrix[i].T) / (norm_train * norm_test[i])
        topk = np.argsort(-cos)[:k]
        neightbor[i] = topk
    return neightbor

In [7]:
def knn_cosine_brute(train_matrix, test_matrix, k):
    neightbor = {}
    for i in range(len(test_matrix)):
        cos = np.array([(cos_sim(test_matrix[i], j)) for j in train_matrix])
        topk = np.argsort(-cos)[:k]
        neightbor[i] = topk
    return neightbor

In [8]:
def Pearson_correlation(train_matrix, test_matrix, k):
    train_matrix = train_matrix-np.mean(train_matrix, axis = 1).reshape(-1,1)
    test_matrix = test_matrix-np.mean(test_matrix, axis = 1).reshape(-1,1)
    neightbor = {}
    norm_train = np.linalg.norm(train_matrix, axis = 1)
    norm_test = np.linalg.norm(test_matrix, axis = 1)
    for i in range(len(test_matrix)):
        denominator = train_matrix @ test_matrix[i].T
        numerator = norm_train * norm_test[i]
        cos = denominator / numerator
        topk = np.argsort(-cos)[:k]
        neightbor[i] = topk
    return neightbor

In [9]:
matrix = np.random.multivariate_normal(np.zeros(100), np.identity(100), 1000)
k = 5
test_matrix = np.random.multivariate_normal(np.zeros(100), np.identity(100), 20)


In [10]:
knn_euclidean(matrix, test_matrix, k)

{0: array([289, 211, 756, 212, 825]),
 1: array([356, 176, 864, 260, 760]),
 2: array([866, 355,  97, 425, 622]),
 3: array([ 87, 988, 895, 914, 439]),
 4: array([212, 801, 414, 368, 927]),
 5: array([818, 926, 381, 778, 891]),
 6: array([109, 499, 866, 423, 490]),
 7: array([264, 245, 960, 604, 734]),
 8: array([930, 959,  25, 914, 439]),
 9: array([140, 880, 813, 563, 190]),
 10: array([174, 880,  95, 909, 323]),
 11: array([323, 700, 658, 879, 959]),
 12: array([666, 904, 176, 604, 893]),
 13: array([  7, 384, 666,  49, 223]),
 14: array([ 87, 960,  61, 260, 633]),
 15: array([890, 360, 145, 690, 520]),
 16: array([433, 498, 325, 801, 746]),
 17: array([445, 116, 604, 772, 697]),
 18: array([188, 644, 220, 605, 793]),
 19: array([483, 363, 473, 230, 100])}

In [11]:
model = NearestNeighbors(n_neighbors= 5, metric='minkowski', algorithm='brute')
model.fit(matrix)
model.kneighbors(test_matrix)[1]

array([[289, 211, 756, 212, 825],
       [356, 176, 864, 260, 760],
       [866, 355,  97, 425, 622],
       [ 87, 988, 895, 914, 439],
       [212, 801, 414, 368, 927],
       [818, 926, 381, 778, 891],
       [109, 499, 866, 423, 490],
       [264, 245, 960, 604, 734],
       [930, 959,  25, 914, 439],
       [140, 880, 813, 563, 190],
       [174, 880,  95, 909, 323],
       [323, 700, 658, 879, 959],
       [666, 904, 176, 604, 893],
       [  7, 384, 666,  49, 223],
       [ 87, 960,  61, 260, 633],
       [890, 360, 145, 690, 520],
       [433, 498, 325, 801, 746],
       [445, 116, 604, 772, 697],
       [188, 644, 220, 605, 793],
       [483, 363, 473, 230, 100]])

In [12]:
model = NearestNeighbors(n_neighbors= 5, metric='cosine', algorithm='brute')
model.fit(matrix)
model.kneighbors(test_matrix)[1]

array([[211, 615, 678, 194,  80],
       [864, 356, 340, 608, 686],
       [ 97, 474, 251, 544, 839],
       [988,  87, 439, 516, 895],
       [212,  42, 927, 595, 948],
       [341, 926, 741, 778, 853],
       [109,  26, 180, 317, 544],
       [264, 734, 204, 860, 245],
       [ 25, 439, 244, 243, 930],
       [140,  14, 813, 563, 880],
       [798, 970, 174, 180, 909],
       [879, 323, 878, 700, 647],
       [116, 904, 612, 221, 587],
       [645, 558, 526,   7, 270],
       [ 87, 956, 960,  61, 991],
       [890, 690,  90, 686, 864],
       [498, 746, 325, 401, 509],
       [116, 755, 445, 134, 182],
       [188, 951, 605, 995, 793],
       [483, 230, 236, 296, 761]])

In [13]:
knn_cosine(matrix, test_matrix, k)

{0: array([211, 615, 678, 194,  80]),
 1: array([864, 356, 340, 608, 686]),
 2: array([ 97, 474, 251, 544, 839]),
 3: array([988,  87, 439, 516, 895]),
 4: array([212,  42, 927, 595, 948]),
 5: array([341, 926, 741, 778, 853]),
 6: array([109,  26, 180, 317, 544]),
 7: array([264, 734, 204, 860, 245]),
 8: array([ 25, 439, 244, 243, 930]),
 9: array([140,  14, 813, 563, 880]),
 10: array([798, 970, 174, 180, 909]),
 11: array([879, 323, 878, 700, 647]),
 12: array([116, 904, 612, 221, 587]),
 13: array([645, 558, 526,   7, 270]),
 14: array([ 87, 956, 960,  61, 991]),
 15: array([890, 690,  90, 686, 864]),
 16: array([498, 746, 325, 401, 509]),
 17: array([116, 755, 445, 134, 182]),
 18: array([188, 951, 605, 995, 793]),
 19: array([483, 230, 236, 296, 761])}

In [14]:
Pearson_correlation(matrix, test_matrix, k)

{0: array([211, 615, 194, 678,  80]),
 1: array([864, 356, 608, 340, 686]),
 2: array([ 97, 474, 251, 544, 839]),
 3: array([988,  87, 439, 516, 427]),
 4: array([ 42, 212, 368, 414, 948]),
 5: array([341, 926, 741, 778, 853]),
 6: array([109,  26, 180, 317, 544]),
 7: array([264, 734, 245, 204, 458]),
 8: array([439,  25, 244, 243, 930]),
 9: array([140,  14, 813, 563, 880]),
 10: array([174, 798, 970, 180, 909]),
 11: array([878, 323, 700, 879, 655]),
 12: array([116, 904, 612, 587, 221]),
 13: array([645, 558, 526, 270, 384]),
 14: array([ 87,  61, 960, 956, 780]),
 15: array([890, 690,  90, 686, 864]),
 16: array([498, 325, 746, 401, 298]),
 17: array([116, 755, 445, 182, 134]),
 18: array([188, 951, 605, 995, 793]),
 19: array([483, 230, 390, 761, 236])}

- Pearson correlation metric is very similar to that of cosine distance. 
    - From the formular, Pearson correlation can be seen as the centralized cosine distance.
    
    
- Most of them are the same, except ```number 9```

In [15]:
cos_sim(test_matrix[0], matrix[674])

-0.002360222694141913

In [16]:
def knn_cosine2(train_matrix, test_matrix, k):
    neightbor = {}
    norm_train = np.linalg.norm(train_matrix, axis = 1)
    norm_test = np.linalg.norm(test_matrix, axis = 1)
    for i in range(len(test_matrix)):
        cos = (train_matrix @ test_matrix[i].T) / (norm_train * norm_test[i])
        topk = np.argsort(-cos)[:k]
        top_cos = -np.sort(-cos)[:k]
        neightbor[i] = [topk,top_cos]
    return neightbor

In [17]:
def knn_euclidean2(train_matrix, test_matrix, k):
    neightbor = {}
    for i in range(len(test_matrix)):
        dist = np.linalg.norm((train_matrix - test_matrix[i].T), axis= 1)
        topk = np.argsort(dist)[:k]
        top_dist = -np.sort(-dist)[:k]
        neightbor[i] = [topk,top_dist]
    return neightbor

In [18]:
def Pearson_correlation2(train_matrix, test_matrix, k):
    train_matrix = train_matrix-np.mean(train_matrix, axis = 1).reshape(-1,1)
    test_matrix = test_matrix-np.mean(test_matrix, axis = 1).reshape(-1,1)
    neightbor = {}
    norm_train = np.linalg.norm(train_matrix, axis = 1)
    norm_test = np.linalg.norm(test_matrix, axis = 1)
    for i in range(len(test_matrix)):
        denominator = train_matrix @ test_matrix[i].T
        numerator = norm_train * norm_test[i]
        cos = denominator / numerator
        topk = np.argsort(-cos)[:k]
        top_cos = -np.sort(-cos)[:k]
        neightbor[i] = [topk,top_cos]
    return neightbor

In [19]:
knn_cosine2(matrix, test_matrix, k)

{0: [array([211, 615, 678, 194,  80]),
  array([0.3290458 , 0.31835469, 0.27511283, 0.2701224 , 0.26696161])],
 1: [array([864, 356, 340, 608, 686]),
  array([0.34493494, 0.31901962, 0.27357732, 0.27001744, 0.26250222])],
 2: [array([ 97, 474, 251, 544, 839]),
  array([0.30731037, 0.30363464, 0.29079658, 0.28586647, 0.27020143])],
 3: [array([988,  87, 439, 516, 895]),
  array([0.35450679, 0.30967128, 0.29468035, 0.26854118, 0.24887457])],
 4: [array([212,  42, 927, 595, 948]),
  array([0.27965181, 0.26464766, 0.25462251, 0.23897476, 0.22954045])],
 5: [array([341, 926, 741, 778, 853]),
  array([0.33118382, 0.32734647, 0.29761022, 0.29248301, 0.28852   ])],
 6: [array([109,  26, 180, 317, 544]),
  array([0.32264976, 0.28058366, 0.26616889, 0.25802081, 0.2539791 ])],
 7: [array([264, 734, 204, 860, 245]),
  array([0.27161011, 0.26355885, 0.23767118, 0.23754133, 0.23315771])],
 8: [array([ 25, 439, 244, 243, 930]),
  array([0.32640418, 0.3099177 , 0.29510517, 0.27574833, 0.26468136])],
 

## Target Users Simulation 


- The reason that we simulate the data is that by doing this, we have a better control of the missing proportion ```threshold```, and it might be a good experiment when dealing with "Cold Start" problem. 


- New Users might not have so many ratings as those in our database. (training data)


### Data Generation Process

- Use data generation process to simulate the data for new users and miss part.

    - Assume each user has a stable preference of choosing rating or not rating. 
       
    - Let $P$ be the event that the entry would be dropped from the artificial matrix.  Then given one user $i$ , the probability of rating or not rating is the same, that is $p_{i}$. 
    
    - For each item of given user, it has probability $p_{i}$ to be dropped out from the matrix.    

        - Generate each $p_{i} \sim U(0, a)$, where $a < 1$, and $a$ is the ```threshold```.
        
        - The reason for setting up the threhold equals to 0.8 instead of 1 is that we don't wanna the $p_{i} = 1$ since otherwise our algorithm won't work.
        
        - Given each user, let $\mathbb{1_{drop}}$ to be a indicator variable denotes whether to drop the rating on item $j$. $\mathbb{1_{drop}} \sim Bern (p_{i})$ 
        
        
        


### Here is an example

<hr style="height:0.5px;">
<br><br>
<img src="Data_generalization.png">
<br><br>
<hr style="height:0.5px;">

In [20]:
test_matrix2 = np.random.multivariate_normal(np.zeros(100), np.identity(100), 40)
train_matrix2 = np.random.multivariate_normal(np.zeros(100), np.identity(100), 1000)


In [21]:
def data_generation(matrix, threshold):
    '''
    - matrix(np array of float): artificial data
    - threshold(float): the upper bound of the missing rate
    - output_matrix (np array of float): artificial data with generated nan 
    '''
    n,m = matrix.shape[0], matrix.shape[1]
    
    p = np.random.uniform(0,threshold, n)
    for i in range(n):
        if p[i] == 0:
            continue
        else:
            ## Each of entry follows Bernoulli Distribution, so the entire row follows Binormial Distribution 
            ## Generate the number of missing data for user i 
            miss_num = np.random.binomial(m, p[i], 1)[0]
            index = random.sample(range(m), miss_num)
            matrix[i, index] = np.nan
    return matrix
            
            

In [22]:
threshold_test = 0.8
threhold_train = 0.1
random.seed(30)
test_matrix2  = data_generation(test_matrix2, threshold_test)
train_matrix2 = data_generation(train_matrix2, threhold_train)
# np.sum(np.isnan(test_matrix), axis = 1)
# np.sum(np.isnan(train_matrix2), axis = 1)

Let $\Omega_{x,y}$ be the set of items where both user $x$ and $y$ rated. $r_{x,i}$ denote rating for user $i$ on item $i$. 

Then 
$$
\operatorname{similarity}(x, y)=\cos (\vec{x}, \vec{y})=\frac{\vec{x} \cdot \vec{y}}{\|\vec{x}\| \times\|\vec{y}\|}=\frac{\sum_{i \in \Omega_{x y}} r_{x, i} r_{y, i}}{\sqrt{\sum_{i \in \Omega_{x}} r_{x, i}^{2}} \sqrt{\sum_{i \in \Omega_{y}} r_{y, i}^{2}}}
$$


### Some Problems:

* Based on the formular, the rating vectors would be highly sparse, and only the rating in the set $\Omega_{x,y}$ would be taken into our calculation. 


### Solution:


There is a trick for calculating the cosine similarity between the sparse vector $A$ and $B$ is to <strong>assign 0 </strong>to the ```nan``` term.


For example, array $A$  = array([  1.,   4.,   2.,  nan,   3.]), $B$ = array([ nan,  nan,   2.,   4.,   1.]).

The dot product $A \cdot B = (1 \cdot nan) + (4 \cdot nan) + (2 \cdot 2) + (nan \cdot 4) + (3 \cdot 1)$. We only care about the $A_{i}$ and $B_{i}$ that are <strong>both not </strong> ```nan```.


Therefore, we ignore all of the ```nan``` terms and only keep $(2 \cdot 2) + (3 \cdot 1) = 7$


Since $A$ and $B$ can be any arbitrary vector, $\left\Vert{A}\right\Vert$ or $\left\Vert{B}\right\Vert$ would be the same case. $\left\Vert{A}\right\Vert= \sqrt{A^{T} A}$, and the rest derivation would be the same. 


#### Before change: 


    - array([[        nan,  0.85219322,  0.03639481, ...,         nan,
            -0.53096698,         nan],
           [-0.95952211,  0.19562883,         nan, ..., -0.57070051,
                nan,         nan],
           [        nan,  0.53597783,         nan, ..., -0.87058322,
               -0.14354887,  0.77974504],
           ...,
           [ 0.34881448,         nan, -0.4747643 , ...,         nan,
             0.26291857,  0.74074827],
           [        nan, -1.49807325, -0.36615501, ..., -0.05927307,
                    nan,  0.66986875],
           [        nan,         nan,  1.31932065, ...,  0.09099651,
                    nan,         nan]])



#### After change: 


    - array([[ 0.        ,  0.85219322,  0.03639481, ...,  0.        ,
        -0.53096698,  0.        ],
       [-0.95952211,  0.19562883,  0.        , ..., -0.57070051,
         0.        ,  0.        ],
       [ 0.        ,  0.53597783,  0.        , ..., -0.87058322,
        -0.14354887,  0.77974504],
       ...,
       [ 0.34881448,  0.        , -0.4747643 , ...,  0.        ,
         0.26291857,  0.74074827],
       [ 0.        , -1.49807325, -0.36615501, ..., -0.05927307,
         0.        ,  0.66986875],
       [ 0.        ,  0.        ,  1.31932065, ...,  0.09099651,
         0.        ,  0.        ]])



Therefore, our recommend algorithm becomes very simple: 
   
   - 1. Find ```nan``` term position and convert to 0
   
   
   - 2. Choose an appropriate similarity metric and finish recommendation

In [23]:
def recommend(train_matrix, test_matrix, k, metric):
    
    train_matrix = np.where(np.isnan(train_matrix),0,train_matrix)
    test_matrix = np.where(np.isnan(test_matrix),0,test_matrix)
    if metric == 'cosine':
        return knn_cosine2(train_matrix, test_matrix, k)
    elif metric == 'euclidean':
        return knn_euclidean2(train_matrix, test_matrix, k)   
    elif metric == 'Peason':
        return Pearson_correlation2(train_matrix, test_matrix, k)
    

In [24]:
recommend_matrix  = recommend(train_matrix2, test_matrix2, k = 5, metric = 'cosine')
recommend_matrix

{0: [array([367, 617, 459, 558, 126]),
  array([0.26883845, 0.26793302, 0.25842686, 0.25287088, 0.23756672])],
 1: [array([299, 414, 125, 678, 486]),
  array([0.32967686, 0.32850284, 0.30071541, 0.30016331, 0.28440624])],
 2: [array([514, 605, 469, 877, 555]),
  array([0.28153569, 0.27967002, 0.27234188, 0.2671912 , 0.25601659])],
 3: [array([580, 245, 412, 348, 138]),
  array([0.31794885, 0.25779714, 0.23483914, 0.23073941, 0.22835541])],
 4: [array([637, 175, 307, 233, 567]),
  array([0.32013892, 0.31773191, 0.26806747, 0.25999116, 0.25699336])],
 5: [array([ 10, 207, 751, 942, 545]),
  array([0.3277439 , 0.28022501, 0.27538722, 0.27115732, 0.27038886])],
 6: [array([137, 445, 636, 144, 884]),
  array([0.2916728 , 0.2914072 , 0.27994746, 0.25487281, 0.24495041])],
 7: [array([  9, 465, 300, 711, 419]),
  array([0.31335293, 0.30607488, 0.29928262, 0.29793504, 0.26106972])],
 8: [array([ 44, 852, 583, 950, 643]),
  array([0.39063421, 0.36559047, 0.36054409, 0.27604022, 0.2701158 ])],
 

## Prediction 


The prediction $P_{u, i }$ is given by 
$$
P_{u,i}=\frac{\sum_{v}\left(r_{v, i} \cdot s_{u, v}\right)}{\sum_{v} s_{u, v}}
$$

where 
* $P_{u,i}$ is the prediction of an item
* $R_{v,i}$ is the rating given by a user $v$ to a movie $i$
* $S_{u,v}$ is the similarity between users

### Prediction Algorithm Peusudocode: 

- For each user in test_matrix: 

    - Find the most similar k ones and the corrsponding similarity between these two. (recommend matrix)
    
        - For each similiar user:
    
             - Find out the correspoding rating (training matrix)
               
             - Calculate $r_{v, i} \cdot s_{u, v}$ 
        
        - Normalize the score by the total similarity. 
 
        - Assign the normalized score to test user $i$

- Finish prediction
            
         
    

In [25]:
def predict(recommend_matrix, test_matrix, train_matrix):
    predict_matrix = test_matrix.copy()
    train_matrix = np.where(np.isnan(train_matrix),0,train_matrix)
    for i in range(len(predict_matrix)):
        id_s, cos = recommend_matrix[i][0], recommend_matrix[i][1]
        score = 0
        normalization = cos.sum()
        for j in range(len(id_s)):
            score += train_matrix[id_s[j]] * cos[j]
        predict_matrix[i] = score/normalization
    return predict_matrix

                
        

In [26]:
prediction = predict(recommend_matrix, test_matrix2, train_matrix2)
prediction

array([[-0.31845256,  0.6785868 , -0.10221802, ..., -0.60886855,
         0.12854086,  0.18045503],
       [-1.43772708,  0.29922262,  0.66382105, ..., -0.04111721,
        -0.61205164,  0.07936011],
       [-0.2482317 , -0.39489954, -0.27574779, ...,  0.0900043 ,
         0.28068771, -0.51815233],
       ...,
       [-0.53848214,  0.14769261,  0.03509299, ..., -0.99993866,
        -0.147392  , -0.50592911],
       [ 0.57478965, -0.35245785, -0.031045  , ..., -0.49016977,
        -0.14229614,  0.32701247],
       [ 0.78153718, -0.35431667, -0.39051795, ...,  0.61615279,
        -0.50229709, -0.05609895]])

## Evaluate (not sure)


The idea comes from the evaluate method of Matrix Factorization (ALS method)

That is 

$$
RMSE = \sqrt{\frac{1}{n} \cdot \sum_{i,j} \left|M_{i j}-\hat{M_{i j}}\right|^{2}}
$$

where $(i,j) \in \Omega$ (observed).


* $n$ is the number of the total predictions (~ nan).


* $M_{i j}$ is the orginal test matrix. (highly sparse)


* $\hat{M_{i j}}$ is the predicted matrix. (no missing data)




In [27]:
def evaluate(test_matrix, predicted_matrix):
    nan_pos = ~np.isnan(test_matrix)
    num_nan = (~np.isnan(test_matrix)).sum()
    RMSE = ((test_matrix[nan_pos] - predicted_matrix[nan_pos])** 2).sum() * (1/num_nan)
    return RMSE ** 0.5

In [28]:
evaluate(test_matrix2, prediction)

0.7814830214776919

## Rating Scale Approach


* Rating scale approach: where a threshold is set and all the movies above that threshold are recommended.



In [29]:
def rating_scale(train_matrix, test_matrix, threshold):
    neightbor = {}
    norm_train = np.linalg.norm(train_matrix, axis = 1)
    norm_test = np.linalg.norm(test_matrix, axis = 1)
    for i in range(len(test_matrix)):
        cos = (train_matrix @ test_matrix[i].T) / (norm_train * norm_test[i])
        cos_kept = []
        cos_index = []
        for j in range(len(cos)):
            if cos[j] >= threshold:
                cos_kept.append(cos[j])
                cos_index.append(j)
#       cos_kept = cos[cos >= threshold]

        neightbor[i] = [cos_index,cos_kept]
    return neightbor

### Rating Scale Approach v.s. Top n Approach


* 1. The user that the system recommend is very similar to that of by Top n approach.


* 2. The users that recommended to our new users are guarantee to have high similiarity.       


* 3. If the threshold that we set up is high, it would result in an empty list situation. That means there is no similar user to recommend. 
   
   


In [30]:
random.seed(0)
train_matrix3 = np.random.multivariate_normal(np.zeros(100), np.identity(100), 1000)
test_matrix3 = np.random.multivariate_normal(np.zeros(100), np.identity(100), 40)
scale = 0.3
rec = rating_scale(train_matrix3, test_matrix3, scale)
rec

{0: [[582, 659], [0.3303032828766637, 0.3716934831862149]],
 1: [[637, 805], [0.30858770806948954, 0.31128586022737387]],
 2: [[534, 875], [0.33250796350179196, 0.3459024555919765]],
 3: [[197], [0.3030792478162777]],
 4: [[577], [0.33339970171168576]],
 5: [[632], [0.3204999067918686]],
 6: [[437], [0.34040625359142007]],
 7: [[630, 696], [0.30177549511805635, 0.31396681346384614]],
 8: [[88], [0.33272808418871563]],
 9: [[179, 778], [0.36229599631067844, 0.30534465564246677]],
 10: [[267, 603], [0.35413512998785435, 0.3073897875705601]],
 11: [[239, 514, 680],
  [0.33369753887100057, 0.31685539406905255, 0.3157191642402268]],
 12: [[89, 761], [0.32654563366468997, 0.3404135494168592]],
 13: [[374, 458, 609, 786, 833],
  [0.3366271835375453,
   0.3311494226585573,
   0.3401700804120999,
   0.3382897368679628,
   0.3668158384927615]],
 14: [[62], [0.3013480137149904]],
 15: [[66, 132], [0.30864586659173976, 0.361744201993073]],
 16: [[789], [0.3416252405743555]],
 17: [[], []],
 18: [[

In [31]:
knn_cosine2(train_matrix3, test_matrix3, k = 3)

{0: [array([659, 582, 706]), array([0.37169348, 0.33030328, 0.27790668])],
 1: [array([805, 637, 794]), array([0.31128586, 0.30858771, 0.27382839])],
 2: [array([875, 534, 381]), array([0.34590246, 0.33250796, 0.29493481])],
 3: [array([197, 351, 567]), array([0.30307925, 0.29291999, 0.28024302])],
 4: [array([577,  42, 628]), array([0.3333997 , 0.29441229, 0.27804519])],
 5: [array([632, 477, 495]), array([0.32049991, 0.27317848, 0.25993029])],
 6: [array([437, 267, 762]), array([0.34040625, 0.29994601, 0.2665654 ])],
 7: [array([696, 630, 421]), array([0.31396681, 0.3017755 , 0.26741943])],
 8: [array([ 88, 863, 235]), array([0.33272808, 0.2924258 , 0.26720583])],
 9: [array([179, 778, 441]), array([0.362296  , 0.30534466, 0.28849207])],
 10: [array([267, 603, 803]), array([0.35413513, 0.30738979, 0.28416682])],
 11: [array([239, 514, 680]), array([0.33369754, 0.31685539, 0.31571916])],
 12: [array([761,  89, 798]), array([0.34041355, 0.32654563, 0.27633357])],
 13: [array([833, 609,

## Assemble to a method

In [32]:
class Content_based_Recommendation():
    
    def __init__(self, train_matrix, test_matrix, metric):
        
        '''
        - train_matrix (numpy.array of matrix): rating matrix for users in our dataset with a few missing term.
        
        - test_matrix (numpy.array of matrix): rating matrix for new users with many missing term. 
        
        - metric (string): different recommendation approachs- 
                            {top_n approachs: [cosine, euclidean, Pearson correltion], 
                             scale_rating: [cosine]
                            }
                            
        '''
        
        self.train_matrix = train_matrix
        self.test_matrix = test_matrix
        self.metric = metric
        
        
    
    def knn_cosine2(self, k):
        neightbor = {}
        norm_train = np.linalg.norm(self.train_matrix, axis = 1)
        norm_test = np.linalg.norm(self.test_matrix, axis = 1)
        for i in range(len(self.test_matrix)):
            cos = (self.train_matrix @ self.test_matrix[i].T) / (norm_train * norm_test[i])
            topk = np.argsort(-cos)[:k]
            top_cos = -np.sort(-cos)[:k]
            neightbor[i] = [topk,top_cos]
        
    
    def knn_euclidean2(self, k):
        neightbor = {}
        for i in range(len(self.test_matrix)):
            dist = np.linalg.norm((self.train_matrix - self.test_matrix[i].T), axis= 1)
            topk = np.argsort(dist)[:k]
            top_dist = -np.sort(-dist)[:k]
            neightbor[i] = [topk,top_dist]
            
    
    def Pearson_correlation2(self, k):
        
        train_matrix = self.train_matrix-np.mean(self.train_matrix, axis = 1).reshape(-1,1)
        test_matrix = self.test_matrix-np.mean(self.test_matrix, axis = 1).reshape(-1,1)
        neightbor = {}
        norm_train = np.linalg.norm(train_matrix, axis = 1)
        norm_test = np.linalg.norm(test_matrix, axis = 1)
        for i in range(len(test_matrix)):
            denominator = train_matrix @ test_matrix[i].T
            numerator = norm_train * norm_test[i]
            cos = denominator / numerator
            topk = np.argsort(-cos)[:k]
            top_cos = -np.sort(-cos)[:k]
            neightbor[i] = [topk,top_cos]
        
    
    def rating_scale(self, threshold):
        neightbor = {}
        norm_train = np.linalg.norm(self.train_matrix, axis = 1)
        norm_test = np.linalg.norm(self.test_matrix, axis = 1)
        for i in range(len(self.test_matrix)):
            cos = (self.train_matrix @ self.test_matrix[i].T) / (norm_train * norm_test[i])
            cos_kept = []
            cos_index = []
            for j in range(len(cos)):
                if cos[j] >= threshold:
                    cos_kept.append(cos[j])
                    cos_index.append(j)
            neightbor[i] = [cos_index,cos_kept]
            
    
    def recommend(self, k):
        
        train_matrix = np.where(np.isnan(self.train_matrix),0,self.train_matrix)
        test_matrix = np.where(np.isnan(self.test_matrix),0,self.test_matrix)
        metric = self.metric
        if metric == 'cosine':
            self.recommend_matrix = knn_cosine2(train_matrix, test_matrix, k)
        elif metric == 'euclidean':
            self.recommend_matrix = knn_euclidean2(train_matrix, test_matrix, k)   
        elif metric == 'Peason':
            self.recommend_matrix = Pearson_correlation2(train_matrix, test_matrix, k)
        elif metric == 'Scale_Rating':
            self.recommend_matrix = Pearson_correlation2(train_matrix, test_matrix, k)
        return self.recommend_matrix
    
    
    
    def get_recommend(self,k):
        self.recommend_matrix = recommend(self,k)
        return self.recommend_matrix
    
    
    def predict(self): 
        predict_matrix = self.test_matrix.copy()
        train_matrix = np.where(np.isnan(self.train_matrix),0,self.train_matrix)
        for i in range(len(predict_matrix)):
            id_s, cos = self.recommend_matrix[i][0], self.recommend_matrix[i][1]
            score = 0
            normalization = cos.sum()
            for j in range(len(id_s)):
                score += train_matrix[id_s[j]] * cos[j]
            predict_matrix[i] = score/normalization
            
        self.predict_matrix = predict_matrix
        
        return self.predict_matrix
        
    def get_predict_matrix(self):
        self.predict_matrix = predict(self)
        return self.predict_matrix
    
    def evaluate(self):
        nan_pos = ~np.isnan(self.test_matrix)
        num_nan = (~np.isnan(self.test_matrix)).sum()
        RMSE = ((self.test_matrix[nan_pos] - self.predict_matrix[nan_pos])** 2).sum() * (1/num_nan)
        return RMSE ** 0.5
        

In [33]:
model = Content_based_Recommendation(train_matrix3, test_matrix3, 'cosine')

In [34]:
k = 5
model.recommend(k)
model.predict()

array([[-0.05040326,  0.00468338,  0.12453094, ...,  1.43404583,
        -0.5682777 , -0.01076042],
       [-0.35203713, -0.09673517, -0.44227336, ...,  0.24596437,
         0.61367342,  0.01281238],
       [ 0.52109742, -0.10224799,  0.71282331, ..., -0.34219465,
         0.15558906, -0.44953842],
       ...,
       [ 0.93559918, -0.13669867,  0.98377471, ..., -1.04650791,
        -0.11718168, -0.32918681],
       [-0.48585568, -0.52786607,  0.55069429, ...,  0.39327948,
        -0.39115754,  0.05128761],
       [ 0.03020775,  0.09453208, -0.49272892, ...,  0.78609346,
         1.06114473, -0.45079808]])

In [35]:
model.evaluate()

0.8240284217098169

## Experiment


### Cold Start Problem


* New User Cold Start: when a new user is introduced in the dataset, there is no history of that user. It becomes harder to recommend products to that user.


* Product Cold Start: when a new product comes out to the market.


### Simulate Cold Start Problem in data generation process




* Set the upper bound for the parameter $p$ to be small for users matrix that is already in our dataset,  and to be extremely small $p = 0.01$ or $p = 0.05$ for new users matrix (test matrix)

In [65]:
# train_matrix4 = np.random.multivariate_normal(np.zeros(100), np.identity(100), 1000)
# test_matrix4 = np.random.multivariate_normal(np.zeros(100), np.identity(100), 40)
threshold_test = 0.99
threhold_train = 0.5
test_matrix4  = data_generation(test_matrix3, threshold_test)
train_matrix4 = data_generation(train_matrix3, threhold_train)

In [70]:
test_matrix4[10]

array([       nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
       1.90494915,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan, 0.48129226,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan, 0.26216648,        nan,        nan,
              nan, 0.21366677,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan,        nan,        nan,        nan,
              nan,        nan, 0.42607402,        nan,        

In [71]:
for i in range(len(test_matrix4)):
    
    if np.isnan(test_matrix4[i]).all():
        print(i)
        



In [72]:
model2 = Content_based_Recommendation(train_matrix4, test_matrix4, 'cosine')
k = 5
model2.recommend(k)
model2.predict()

array([[ 0.42528922,  0.39082204,  1.1384523 , ...,  0.08201892,
         0.89072398, -0.05426291],
       [ 0.18446023,  0.17822265,  0.14977251, ...,  0.22242213,
        -0.17770872, -0.08597488],
       [ 0.06804722,  0.        ,  0.02219324, ...,  0.06754473,
        -0.13359436, -0.23451056],
       ...,
       [ 0.23352943, -0.04632696,  0.03410624, ..., -0.43128783,
         0.39984582, -0.12592533],
       [ 0.45600146,  0.17013748,  0.11948956, ..., -0.25256263,
        -0.56509147, -0.14408346],
       [-0.03659217, -0.23955437,  0.08318718, ...,  0.07719427,
         0.04067955,  0.15962261]])

In [73]:
model2.evaluate()

0.704806602809465

### The manual featured data

In [36]:
import pandas as pd
manual_data = pd.read_csv('manual_data.csv')
manual_data

item no(left to right)  Male/Female  patten/ non-patten  blue/non-blue  \
0                       1            0                   1              1   
1                       2            0                   0              1   
2                       3            0                   1              0   
3                       4            1                   0              1   
4                       5            1                   1              0   

   black/non-black  green/non-green  color scale  collar  short sleeve/long  
0                0                0          0.5       1                  0  
1                0                0          0.9       1                  0  
2                1                0          1.0       1                  0  
3                0                0          0.3       0                  0  
4                0                1          0.5       0                  1