In [7]:
from PIL import Image
#读读片
image = Image.open('image2/1.png')

In [9]:
print(image.format)
print(image.size)
print(image.mode)
# show the image
image.show()

PNG
(136, 207)
RGBA


In [13]:
#转换 
from numpy import asarray

data1 = asarray(image)
print(type(data1))
print(data1.shape)

image2 = Image.fromarray(data1)
print(type(image2))
print(image2.mode)
print(image2.size)

<class 'numpy.ndarray'>
(207, 136, 4)
<class 'PIL.Image.Image'>
RGBA
(136, 207)


In [14]:
print(data1)

[[[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [201 201 201 255]
  ...
  [200 199 205 255]
  [200 199 205 255]
  [200 199 205 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [201 201 201 255]
  ...
  [200 199 205 255]
  [200 199 205 255]
  [200 199 205 255]]

 ...

 [[255 255 255 255]
  [255 255 255 255]
  [212 210 221 255]
  ...
  [179 179 179 255]
  [179 179 179 255]
  [180 180 180 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]]


In [17]:
import numpy as np
#resize pic
load_img_rz = np.array(Image.open('image2/1.png').resize((20,20)))
Image.fromarray(load_img_rz).save('image2/1_1.png')
print("After resizing:",load_img_rz.shape)

After resizing: (20, 20, 4)


In [26]:
def resize(a):
    load_img_rz = np.array(Image.open('image3/'+a).resize((8,8)))
    Image.fromarray(load_img_rz).save('image3/'+a)    

 

In [27]:
#全部resize 成8*8的图片
import os,sys
name = os.listdir('image3/')
for a in name:
    resize(a)

In [28]:
#全部变成向量，每一个向量代表一个像素
image1 = Image.open('image3/1.png')
data1 = asarray(image1)
print(data1)

[[[210 210 211 255]
  [217 216 214 255]
  [201 197 198 255]
  [172 121 102 255]
  [139 123 131 255]
  [185 194 208 255]
  [215 212 215 255]
  [208 207 212 255]]

 [[217 216 218 255]
  [151 172 197 255]
  [ 63 115 168 255]
  [ 77 109 144 255]
  [ 47 112 168 255]
  [ 47 117 179 255]
  [ 98 142 185 255]
  [197 201 211 255]]

 [[222 219 223 255]
  [ 84 125 175 255]
  [ 28 110 175 255]
  [ 40 133 183 255]
  [ 43 137 184 255]
  [ 35 109 168 255]
  [ 22  91 161 255]
  [126 155 188 255]]

 [[223 223 227 255]
  [154 148 161 255]
  [ 46 106 160 255]
  [ 43 133 182 255]
  [ 42 129 178 255]
  [ 32 109 168 255]
  [111 123 146 255]
  [174 142 128 255]]

 [[219 214 216 255]
  [197 156 139 255]
  [ 56 108 158 255]
  [ 41 130 181 255]
  [ 44 134 183 255]
  [ 38 122 176 255]
  [155 157 166 255]
  [199 138 104 255]]

 [[219 203 196 255]
  [153 135 140 255]
  [ 34 108 172 255]
  [ 43 131 182 255]
  [ 45 139 187 255]
  [ 41 130 184 255]
  [147 155 167 255]
  [186 134 110 255]]

 [[207 166 150 255]
  [114 1

In [70]:
image2 = Image.open('image3/2.png')
data2 = asarray(image2)
image3 = Image.open('image3/3.png')
data3 = asarray(image3)
image4 = Image.open('image3/4.png')
data4 = asarray(image4)
image5 = Image.open('image3/5.png')
data5 = asarray(image5)

In [71]:
#计算色差,可以无脑用欧氏距离，这里用的是一个加权的欧式距离
import math
def colordist(a,b):
    R=int(a[0])-int(b[0])
    G=int(a[1])-int(b[1])
    B=int(a[2])-int(b[2])
    rmean=(int(a[0])+int(b[0]))/2
    return math.sqrt((2+rmean/256)*(R**2)+4*(G**2)+(2+(255-rmean)/256)*(B**2))
    

In [72]:
#通过3维的色差计算欧式距离
def picdist(d1,d2):
    d=0  
    for i in range(8):
        for j in range(8):
            d = d+(colordist(d1[i,j],d2[i,j])**2)
    return math.sqrt(d)

In [74]:
print(picdist(data3,data1))
print(picdist(data3,data2))
print(picdist(data3,data4))
print(picdist(data3,data5))
#得出和第二件比较接近

1776.1133029296723
1232.3002159642856
3025.893633176301
2849.0605030430647


In [76]:
#转换成灰度，可以1.避免亮度饱和度等对色差的影响 2.计算时候可以使用余弦距离进行计算
def hui(a):
    load_img_rz = np.array(Image.open('image4/'+a).convert('L'))
    Image.fromarray(load_img_rz).save('image4/'+a)    

name = os.listdir('image4/')
for b in name:
    hui(b)

In [77]:
#全部变成向量，每一个数字代表一个像素的灰度
image1 = Image.open('image4/1.png')
data1 = asarray(image1)
print(data1)

[[210 216 198 134 129 193 213 208]
 [217 169 105 103  99 103 134 201]
 [220 118  93 111 114  94  78 150]
 [223 151  94 112 109  93 122 150]
 [216 166  98 109 113 103 157 152]
 [207 141  93 111 116 110 154 147]
 [176 115  85  97  99  74 133 155]
 [176  96  53  50  54  51 138 165]]


In [81]:
image2 = Image.open('image4/2.png')
data2 = asarray(image2)
image3 = Image.open('image4/3.png')
data3 = asarray(image3)
image4 = Image.open('image4/4.png')
data4 = asarray(image4)
image5 = Image.open('image4/5.png')
data5 = asarray(image5)

In [94]:
#通过灰度直接去计算余弦距离
import numpy as np
import pandas as pd
def bit_product_sum(x, y):
    return sum([item[0] * item[1] for item in zip(x, y)])

def cosine_similarity(x, y):
    cos = bit_product_sum(x, y) / (np.sqrt(bit_product_sum(x, x)) * np.sqrt(bit_product_sum(y, y)))
    return cos 


In [88]:
def tran64(a):
    b=np.zeros(shape=(64))
    for i in range(8):
        for j in range(8):
            b[i*8+j]=int(a[i,j])
    return b

dat1= tran64(data1)
dat2= tran64(data2)
dat3= tran64(data3)
dat4= tran64(data4)
dat5= tran64(data5)

In [96]:
print(cosine_similarity(dat3,dat1))
print(cosine_similarity(dat3,dat2))
print(cosine_similarity(dat3,dat4))
print(cosine_similarity(dat3,dat5))

0.9161593519971645
0.9519940477385038
0.8464963666587378
0.8647158263324242
