In [1]:
import numpy as np
import pandas as pd

In [2]:
def load_data(path):
    data = pd.read_csv(path)

    return data

In [3]:
def findCosineDistance(dataset):
    #subset A to drop item_no column
    A = dataset.drop(['item'],axis=1)
    A = np.array(A)

    similarity = np.dot(A, A.T)
    # squared magnitude of preference vectors (number of occurrences)
    square_mag = np.diag(similarity)
    # inverse squared magnitude
    inv_square_mag = 1 / square_mag
    # inverse of the magnitude
    inv_mag = np.sqrt(inv_square_mag)
    # cosine similarity (elementwise multiply by inverse magnitudes)
    cosine = similarity * inv_mag
    cosine = cosine.T * inv_mag
    #minus the diagnal
    cos = cosine - np.diag(np.diag(cosine))

    return cosine, cos

In [4]:
def KNN(A, item_no):
    #Ranked shirt number by cosine similarity from low to high 
    out_arr_index = np.argsort(A[item_no]) 
    #Output ranked by cosine similarity from low to high
    out_arr = A[item_no][out_arr_index]
    print ("Output sorted array indices/ Ranked shirt number by cosine similarity from low to high: ", out_arr_index) 
    print("Output sorted array/ Output ranked by cosine similarity from low to high: ", out_arr)
    
    return out_arr, out_arr_index

In [5]:
def main():
    path = 'practice_data.csv'
    #Convert the pictures below into item characters
    train_data = load_data(path)
    #Write Calculation of cosine similarity
    cosine, cos = findCosineDistance(train_data)
    print(cos)
    #KNN
    out_arr, out_arr_index = KNN(cos, 1)

In [6]:
if __name__ == '__main__':
    main()

[[0.         0.69624472 0.69337525 0.44124827 0.3363364 ]
 [0.69624472 0.         0.48669974 0.45005759 0.36033882]
 [0.69337525 0.48669974 0.         0.10375717 0.36380344]
 [0.44124827 0.45005759 0.10375717 0.         0.38586042]
 [0.3363364  0.36033882 0.36380344 0.38586042 0.        ]]
Output sorted array indices/ Ranked shirt number by cosine similarity from low to high:  [1 4 3 2 0]
Output sorted array/ Output ranked by cosine similarity from low to high:  [0.         0.36033882 0.45005759 0.48669974 0.69624472]
